import React from 'react';

function About()
{
  return  <main id="about" className="content responsive">
    <p>I have been interested in computers ever since I was a child. My father, who is a prominent figure in the field, often tinkers with different hardware and changes its software. That has always caught my attention and ultimately influenced me to choose the spheres of engineering and computer science. My father always encourages me to do practical experiments on my own. I tirelessly disassemble every device in your house, sometimes leaving a trail of scattered parts around my room. Though you were not able to fix any of the devices you dismantled, this determination to understand the components of every machine piqued your interest in mechanical engineering and encouraged you to devote your academic career to understanding, improving, and inventing more machines. Because those are reasonably complicated fields, I still accumulate many questions and often spend hours finding the answers to them. My first impressions of the fields were very positive, so to deepen my understanding of the subjects, I entered Quantum College, which is a private school. That school enabled me to take various courses from CISCO, which have cemented my opinion that the field of computer science suits me well. Overall, the experiences I've had over the years have been very delightful, which has convinced me that I've made the right decision for my career. I got ecstatic when I become familiar with artificial intelligence and data science. What I find exciting is that Data science allows me to create value from raw, unordered data. Even more appealing is the programming AI, which will never stop developing.</p>
    <p>Fictional literature changes some of my understanding of the situation, possible solution and also it taught me what I love to read. Only when I started reading some international fictional literature did I realize I love educational books. The plots differ from explicitly quoting a piece of advice, solving puzzles and decrypting, presenting kindness in the real ruthless world etc. Not only does satisfying my wishes have to involve books but also Movies, performances, programs, TV shows, short animations, reality shows, Ted-talks, youtube videos, podcasts, magazines, articles, journals. Literally, everything you can learn from did and will at least once catch my attention.</p>
  </main>
}

export default About;
