import Layout from '../components/layout';
import '../styles/projects.css'
import React from 'react';

export default function Projects() {
  return <Layout>
    <div className='content'>
      <div id="minesweeper" className="text">
          <h2>PERFECT MINESWEEPER AI (VISUALIZATION)</h2>
          <p>If you have ever played Minesweeper, there's a good chance that you have bumped into a situation where there is no obvious solution. The Minesweeper is actually a game of luck, which means that even the best players have to guess in some cases to win the game. In order to take the best guess, one must know the probability of bombs in each and every tile. So I have decided to build up a visualization of what would perfect Minesweeper AI see.</p>
          <div>
          <img style={{"maxWidth":"100%","margin":"auto","display":"block"}} src="./Images/Minesweeper/Minesweeper.png" alt="Perfect Minesweeper AI"/>
          </div>
          <p> Above you can see three examples, when a guess is not avoidable when playing the game. There you can see AI visualization map of probabilities. The green tone indicates low probabilty of being a bomb in that square. And the red means high probability. So having AI click on the lowest probability of being a bomb would yield THE PERFECT MINESWEEPER AI.</p>
      </div>
      <div id="fractals" className="text">
          <h1>FRACTALS</h1>
          <p>Have you ever wondered if computers can think Creatively? Well, least they can draw. Have a look and enjoy some of the best fractals I have managed to generate.</p>
          <p>All picture you see are generated by myself and my computer</p>
          <div className="gallery">

            <div className="text">Special Fractals</div>
            <img src="./Images/Fractals/yellow/4.png" alt="Perfect Minesweeper AI"/>
            <img style={{"backgroundColor":"black"}} src="./Images/Fractals/yellow/5.png" alt="Perfect Minesweeper AI"/>
            <img src="./Images/Fractals/yellow/6.png" alt="Perfect Minesweeper AI"/>

          <div className="text">Exorcise the demon from a planet</div>
          <img src="./Images/Fractals/blue/2_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/blue/3_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/blue/4_small.png" alt="Perfect Minesweeper AI"/>

          <div className="text">Spaceship Fractals</div>
          <img src="./Images/Fractals/yellow/1_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/yellow/2_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/yellow/3_small.png" alt="Perfect Minesweeper AI"/>

          <div className="text">Green Fractals</div>
          <img src="./Images/Fractals/green/1_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/green/2_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/green/3_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/green/4_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/green/5_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/green/6_small.png" alt="Perfect Minesweeper AI"/>

          <div className="text">Black and White Fractals</div>
          <img src="./Images/Fractals/black_white/1_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/black_white/2_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/black_white/3_small.png" alt="Perfect Minesweeper AI"/>

          <div className="text">Other Fractals</div>
          <img src="./Images/Fractals/other/1_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/other/2_small.png" alt="Perfect Minesweeper AI"/>
          <img src="./Images/Fractals/other/3_small.png" alt="Perfect Minesweeper AI"/>

          </div>
      </div>
    </div>


  </Layout>;
}