name: Push Docker to Dockerhub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building website
      run: docker build . -t yeranosyanvahan/yeranosyanvahan.com:latest
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u yeranosyanvahan -p $DOCKER_PASSWORD
    - name: Pushing to Docker Registry
      run: docker push yeranosyanvahan/yeranosyanvahan.com:latest
